package com.generics.erasure;

import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.List;

/**
 * Type erasure: generics are a compile-time feature only.
 *
 * <p>After the compiler verifies generic code, it erases all type arguments:
 * <ul>
 *   <li>Unbounded type parameters ({@code T}) erase to {@code Object}.</li>
 *   <li>Bounded parameters ({@code T extends Number}) erase to their bound ({@code Number}).</li>
 *   <li>The compiler inserts casts where needed (hidden from source).</li>
 * </ul>
 *
 * <p>Consequence: at runtime, {@code Box<String>} and {@code Box<Integer>} are
 * the same class.  All parameterized type information is gone.
 */
public class ErasureDemo {

    static class Box<T> {
        private T value;
        Box(T v) { this.value = v; }
        T get()  { return value; }
    }

    // -----------------------------------------------------------------------
    // 1. Box<String> and Box<Integer> share one class object at runtime.
    // -----------------------------------------------------------------------
    public static void showSameClass() {
        Box<String>  strBox = new Box<>("hello");
        Box<Integer> intBox = new Box<>(42);

        System.out.println("strBox.getClass() = " + strBox.getClass().getName());
        System.out.println("intBox.getClass() = " + intBox.getClass().getName());
        System.out.println("Same class object? " + (strBox.getClass() == intBox.getClass()));
    }

    // -----------------------------------------------------------------------
    // 2. instanceof with parameterized types is illegal — type arg is erased.
    //    You can only check the raw type (or use a wildcard).
    // -----------------------------------------------------------------------
    public static void showInstanceOf(Object obj) {
        // if (obj instanceof Box<String>) { }  // compile error — type arg unavailable
        if (obj instanceof Box<?> box) {        // wildcard is fine
            System.out.println("Is a Box. Value (as Object): " + box.get());
        } else {
            System.out.println("Not a Box: " + obj);
        }
    }

    // -----------------------------------------------------------------------
    // 3. List<String> and List<Integer> erase to the same List.
    //    You cannot overload on parameterized types that erase identically.
    //
    //   void process(List<String>  list) { }   // both erase to process(List) — compile error
    //   void process(List<Integer> list) { }
    // -----------------------------------------------------------------------
    @SuppressWarnings("unchecked")
    public static void showListErasure() {
        List<String>  strings = new ArrayList<>();
        List<Integer> ints    = new ArrayList<>();

        // Both erase to java.util.ArrayList at runtime:
        System.out.println("List<String>  class: " + strings.getClass().getName());
        System.out.println("List<Integer> class: " + ints.getClass().getName());
        System.out.println("Same? " + (strings.getClass() == ints.getClass()));

        // The compiler inserted a cast when we retrieved from Box<String>.get().
        // At the bytecode level it is:  (String) box.get()
        // We can prove this by forcing a cast failure via the raw type:
        @SuppressWarnings("rawtypes")
        Box raw = new Box(42);       // stores Integer without any type parameter
        try {
            String s = (String) raw.get();   // cast inserted — fails at runtime
            System.out.println("Unexpected: " + s);
        } catch (ClassCastException e) {
            System.out.println("ClassCastException caught: " + e.getMessage()
                    + " — the erased cast was exposed");
        }
    }

    // -----------------------------------------------------------------------
    // 4. Bridge methods — generated by the compiler for polymorphism.
    //
    //    When a subclass overrides a method with a more specific return type,
    //    the compiler generates a synthetic bridge method with the erased
    //    signature that simply delegates to the real override.
    // -----------------------------------------------------------------------
    static class StringBox extends Box<String> {
        StringBox(String v) { super(v); }

        @Override
        public String get() {        // overrides Box<T>.get() which erases to Object get()
            return super.get().toUpperCase();
        }
    }

    public static void showBridgeMethods() throws Exception {
        System.out.println("Methods declared by StringBox:");
        for (Method m : StringBox.class.getDeclaredMethods()) {
            System.out.printf("  %-45s synthetic=%b%n", m.toGenericString(), m.isSynthetic());
        }
        // You will see two get() methods:
        //   public String get()    ← the one you wrote          synthetic=false
        //   public Object get()    ← the compiler-generated bridge synthetic=true
    }

    // -----------------------------------------------------------------------
    // 5. Restrictions caused by erasure
    // -----------------------------------------------------------------------
    public static void showRestrictions() {
        // (a) Cannot instantiate a type parameter.
        //     new T() is illegal — the class is unknown at runtime.
        //     Workaround: pass a Class<T> or a Supplier<T> from the caller.

        // (b) Cannot create a generic array.
        //     new T[10] is illegal.
        //     Workaround: create Object[] and cast (with unchecked warning).
        @SuppressWarnings("unchecked")
        Box<String>[] boxArray = (Box<String>[]) new Box[3];
        boxArray[0] = new Box<>("a");
        System.out.println("Raw-array workaround: boxArray[0] = " + boxArray[0].get());

        // (c) Cannot use primitives as type arguments.
        //     Box<int> is illegal — use Box<Integer> + autoboxing.
        Box<Integer> intBox = new Box<>(5);   // Integer, not int
        int primitive = intBox.get();         // auto-unboxed
        System.out.println("int from Box<Integer> (auto-unbox): " + primitive);

        // (d) Cannot have static fields of type T — T differs per instantiation
        //     but there is only one static field shared across all instances.
        //     (Shown as a comment — it would be a compile error.)
        //   static T sharedValue;  // compile error

        // (e) Cannot throw or catch a generic exception type.
        //   class MyException<T> extends Exception { }  // cannot extend Throwable generically
        //   catch (MyException<String> e) { }           // compile error
    }
}
