package com.markovmonopoly.core;

import java.io.*;
import java.nio.file.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Loads and saves {@link MarkovChain} objects to plain-text files.
 *
 * <h2>File Format</h2>
 * <pre>
 * # markovchain v1
 * # Lines starting with # are comments.
 * # Blank lines are ignored.
 *
 * NAME WeatherChain
 * DESCRIPTION A simple 3-state weather model
 * STATES 3
 * Sunny
 * Cloudy
 * Rainy
 * MATRIX
 * 0.700000 0.200000 0.100000
 * 0.300000 0.400000 0.300000
 * 0.200000 0.300000 0.500000
 * </pre>
 *
 * <p>State labels may contain spaces (the full trimmed line is used).
 * Probabilities are written with 6 decimal places.
 */
public final class MarkovChainIO {

    private MarkovChainIO() {}

    /** Default directory for saving/loading chains. */
    public static Path defaultDirectory() {
        return Path.of(System.getProperty("user.dir"), "chains");
    }

    // -------------------------------------------------------------------------
    // Save
    // -------------------------------------------------------------------------

    /**
     * Saves a Markov chain to a file.
     *
     * @param chain    the chain to save
     * @param file     destination path (parent directory must exist)
     * @throws IOException if the file cannot be written
     */
    public static void save(MarkovChain chain, Path file) throws IOException {
        Files.createDirectories(file.getParent() != null ? file.getParent() : Path.of("."));
        try (PrintWriter writer = new PrintWriter(Files.newBufferedWriter(file))) {
            write(chain, writer);
        }
    }

    /** Writes the chain to a PrintWriter. */
    public static void write(MarkovChain chain, PrintWriter out) {
        out.println("# markovchain v1");
        out.println("# Generated by MarkovMonopoly");
        out.println();
        out.println("NAME " + chain.getName());
        if (!chain.getDescription().isEmpty()) {
            out.println("DESCRIPTION " + chain.getDescription());
        }
        out.println("STATES " + chain.size());
        for (String label : chain.getStateLabels()) {
            out.println(label);
        }
        out.println("MATRIX");
        TransitionMatrix matrix = chain.getMatrix();
        for (int i = 0; i < chain.size(); i++) {
            StringBuilder sb = new StringBuilder();
            for (int j = 0; j < chain.size(); j++) {
                if (j > 0) sb.append(' ');
                sb.append(String.format("%.6f", matrix.get(i, j)));
            }
            out.println(sb);
        }
    }

    /** Serializes the chain to a String. */
    public static String serialize(MarkovChain chain) {
        StringWriter sw = new StringWriter();
        write(chain, new PrintWriter(sw));
        return sw.toString();
    }

    // -------------------------------------------------------------------------
    // Load
    // -------------------------------------------------------------------------

    /**
     * Loads a Markov chain from a file.
     *
     * @param file path to the file
     * @return the loaded chain
     * @throws IOException              if the file cannot be read
     * @throws IllegalArgumentException if the format is invalid
     */
    public static MarkovChain load(Path file) throws IOException {
        try (BufferedReader reader = Files.newBufferedReader(file)) {
            return parse(reader, file.toString());
        }
    }

    /** Parses a chain from a String. */
    public static MarkovChain deserialize(String text) {
        try {
            return parse(new BufferedReader(new StringReader(text)), "<string>");
        } catch (IOException e) {
            throw new IllegalArgumentException("Failed to parse: " + e.getMessage(), e);
        }
    }

    private static MarkovChain parse(BufferedReader reader, String source) throws IOException {
        String name = "Unnamed";
        String description = "";
        List<String> labels = null;
        double[][] matrix = null;
        int numStates = -1;
        int labelIdx = 0;
        int matrixRow = 0;

        enum Section { HEADER, STATES, MATRIX }
        Section section = Section.HEADER;

        String line;
        int lineNum = 0;

        while ((line = reader.readLine()) != null) {
            lineNum++;
            String trimmed = line.trim();

            // Skip comments and blank lines
            if (trimmed.isEmpty() || trimmed.startsWith("#")) continue;

            switch (section) {
                case HEADER -> {
                    if (trimmed.startsWith("NAME ")) {
                        name = trimmed.substring(5).trim();
                    } else if (trimmed.startsWith("DESCRIPTION ")) {
                        description = trimmed.substring(12).trim();
                    } else if (trimmed.startsWith("STATES ")) {
                        numStates = parseInt(trimmed.substring(7).trim(), lineNum, source);
                        labels = new ArrayList<>(numStates);
                        section = Section.STATES;
                    } else {
                        throw parseError("Unexpected token '" + trimmed + "'", lineNum, source);
                    }
                }
                case STATES -> {
                    if (trimmed.equals("MATRIX")) {
                        if (labels.size() != numStates) {
                            throw parseError("Expected " + numStates + " state labels, got " +
                                labels.size(), lineNum, source);
                        }
                        matrix = new double[numStates][numStates];
                        section = Section.MATRIX;
                    } else {
                        labels.add(trimmed);
                        labelIdx++;
                    }
                }
                case MATRIX -> {
                    if (matrixRow >= numStates) {
                        throw parseError("Extra matrix rows beyond " + numStates, lineNum, source);
                    }
                    String[] parts = trimmed.split("\\s+");
                    if (parts.length != numStates) {
                        throw parseError("Row " + matrixRow + " has " + parts.length +
                            " values, expected " + numStates, lineNum, source);
                    }
                    for (int j = 0; j < numStates; j++) {
                        try {
                            double v = Double.parseDouble(parts[j]);
                            if (v < 0) throw parseError(
                                "Negative probability " + v + " at row " + matrixRow + " col " + j,
                                lineNum, source);
                            matrix[matrixRow][j] = v;
                        } catch (NumberFormatException e) {
                            throw parseError("Invalid number '" + parts[j] + "'", lineNum, source);
                        }
                    }
                    matrixRow++;
                }
            }
        }

        if (labels == null || matrix == null) {
            throw new IllegalArgumentException(
                "File '" + source + "' is missing STATES or MATRIX section.");
        }
        if (matrixRow != numStates) {
            throw new IllegalArgumentException(
                "File '" + source + "': expected " + numStates + " matrix rows, got " + matrixRow);
        }

        return new MarkovChain(name, description, labels, TransitionMatrix.of(matrix).normalized());
    }

    private static int parseInt(String s, int lineNum, String source) {
        try {
            return Integer.parseInt(s);
        } catch (NumberFormatException e) {
            throw parseError("Expected integer, got '" + s + "'", lineNum, source);
        }
    }

    private static IllegalArgumentException parseError(String msg, int lineNum, String source) {
        return new IllegalArgumentException(
            "Parse error in '" + source + "' at line " + lineNum + ": " + msg);
    }
}
